# Generated by Django 2.2.2 on 2019-09-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguiar',
            name='rut',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='Rut Empresa'),
        ),
    ]
