# Generated by Django 2.2.5 on 2019-11-14 02:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaResultadosDotacion',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cant_emp_contratados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_emp_contratista', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_veh_empresa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_veh_contratista', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_veh_empresa_pesado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_veh_contratista_pesado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_maq_pesada_empresa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_maq_pesada_contratista', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TablaVentasAnuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TablaPerfilEmpresa',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experiencia_empresa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ciudad_empresa', models.CharField(default='', max_length=20)),
                ('comuna_empresa', models.CharField(default='', max_length=20)),
                ('razon_social_empresa', models.CharField(default='', max_length=100)),
                ('nombre_representante', models.CharField(default='', max_length=50)),
                ('rut_representante', models.CharField(max_length=12)),
                ('email_representante', models.EmailField(default='', max_length=50)),
                ('telefono_representante', models.CharField(default='', max_length=15)),
                ('ventas_anuales_empresa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaVentasAnuales')),
            ],
        ),
    ]
