# Generated by Django 2.2.2 on 2019-09-12 21:56

import Poll.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tabla_perfil_usuario',
            managers=[
                ('objects', Poll.models.UsuarioManager()),
            ],
        ),
    ]
