# Generated by Django 2.2.2 on 2019-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_usuario',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tabla_usuario',
            name='rut_empresa',
            field=models.CharField(default='', max_length=15),
        ),
    ]
