# Generated by Django 2.2.5 on 2019-11-12 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaVentasAnuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TablaPerfilEmpresa',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experiencia_empresa', models.IntegerField(default=0)),
                ('ciudad_empresa', models.CharField(default='', max_length=20)),
                ('comuna_empresa', models.CharField(default='', max_length=20)),
                ('razon_social_empresa', models.CharField(default='', max_length=100)),
                ('nombre_representante', models.CharField(default='', max_length=50)),
                ('rut_representante', models.CharField(max_length=12)),
                ('email_representante', models.EmailField(default='', max_length=50)),
                ('telefono_representante', models.CharField(default='', max_length=15)),
                ('ventas_anuales_empresa', models.ManyToManyField(to='Poll.TablaVentasAnuales')),
            ],
        ),
    ]
