# Generated by Django 2.2.2 on 2019-09-15 02:37

import Poll.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_auto_20190912_2333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userguiar',
            managers=[
                ('objects', Poll.models.UserGuiarManager()),
            ],
        ),
    ]
