# Generated by Django 2.2.2 on 2019-09-15 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_tablaresultadostransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaResultadosContruccion',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosDotacion',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.CharField(default='', max_length=10)),
                ('answer2', models.CharField(default='', max_length=10)),
                ('answer3', models.CharField(default='', max_length=10)),
                ('answer4', models.CharField(default='', max_length=10)),
                ('answer5', models.CharField(default='', max_length=10)),
                ('answer6', models.CharField(default='', max_length=10)),
                ('answer7', models.CharField(default='', max_length=10)),
                ('answer8', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosElectricidad',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosExplosivos',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosFinales',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('riesgo_transporte', models.CharField(default='', max_length=3)),
                ('riesgo_construccion', models.CharField(default='', max_length=3)),
                ('riesgo_manufactura', models.CharField(default='', max_length=3)),
                ('riesgo_servicios', models.CharField(default='', max_length=3)),
                ('riesgo_dotacion', models.CharField(default='', max_length=3)),
                ('riesgo_gestion', models.CharField(default='', max_length=3)),
                ('riesgo_procesos', models.CharField(default='', max_length=3)),
                ('riesgo_explosivos', models.CharField(default='', max_length=3)),
                ('riesgo_electricidad', models.CharField(default='', max_length=3)),
                ('riesgo_sustancias_peligrosas', models.CharField(default='', max_length=3)),
                ('riesgo_altura', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosGestion',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
                ('answer7', models.BooleanField(default=False)),
                ('answer8', models.BooleanField(default=False)),
                ('answer9', models.BooleanField(default=False)),
                ('answer10', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosManufactura',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosProcesos',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosRiesgoAltura',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosServicios',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
                ('answer7', models.BooleanField(default=False)),
                ('answer8', models.BooleanField(default=False)),
                ('answer9', models.BooleanField(default=False)),
                ('answer10', models.BooleanField(default=False)),
                ('answer11', models.BooleanField(default=False)),
                ('answer12', models.BooleanField(default=False)),
                ('answer13', models.BooleanField(default=False)),
                ('answer14', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosSustanciasPeligrosas',
            fields=[
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answer1', models.BooleanField(default=False)),
                ('answer2', models.BooleanField(default=False)),
                ('answer3', models.BooleanField(default=False)),
                ('answer4', models.BooleanField(default=False)),
                ('answer5', models.BooleanField(default=False)),
                ('answer6', models.BooleanField(default=False)),
                ('answer7', models.BooleanField(default=False)),
                ('answer8', models.BooleanField(default=False)),
                ('answer9', models.BooleanField(default=False)),
            ],
        ),
    ]
