# Generated by Django 2.2.3 on 2019-09-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_tablaresultadoscontruccion_tablaresultadosdotacion_tablaresultadoselectricidad_tablaresultadosexplos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_perfil_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='', max_length=100)),
                ('rut_empresa', models.CharField(default='', max_length=15)),
                ('direccion_empresa', models.CharField(default='', max_length=100)),
                ('experiencia_empresa', models.CharField(default='', max_length=10)),
                ('ciudad_empresa', models.CharField(default='', max_length=20)),
                ('comuna_empresa', models.CharField(default='', max_length=20)),
                ('razon_social_empresa', models.CharField(default='', max_length=100)),
                ('ventas_anuales_empresa', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_perfil_empresa')),
            ],
        ),
    ]
