# Generated by Django 2.2.3 on 2019-07-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20190731_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_resultados_transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('answer7', models.CharField(default='', max_length=2)),
                ('answer8', models.CharField(default='', max_length=2)),
                ('answer9', models.CharField(default='', max_length=2)),
                ('answer10', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('answer7', models.CharField(default='', max_length=2)),
                ('answer8', models.CharField(default='', max_length=2)),
                ('answer9', models.CharField(default='', max_length=2)),
                ('answer10', models.CharField(default='', max_length=2)),
                ('answer11', models.CharField(default='', max_length=2)),
                ('answer12', models.CharField(default='', max_length=2)),
                ('answer13', models.CharField(default='', max_length=2)),
                ('answer14', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_manufactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_construccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('answer7', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
    ]
