# Generated by Django 2.2.5 on 2019-11-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20191114_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='ventas_anuales_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaVentasAnuales'),
        ),
    ]
