# Generated by Django 2.2.3 on 2019-09-25 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_tablaresultadoscontruccion_tablaresultadosdotacion_tablaresultadoselectricidad_tablaresultadosexplos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPerfilEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='', max_length=100)),
                ('direccion_empresa', models.CharField(default='', max_length=100)),
                ('experiencia_empresa', models.CharField(default='', max_length=10)),
                ('ciudad_empresa', models.CharField(default='', max_length=20)),
                ('comuna_empresa', models.CharField(default='', max_length=20)),
                ('razon_social_empresa', models.CharField(default='', max_length=100)),
                ('ventas_anuales_empresa', models.CharField(default='', max_length=50)),
                ('nombre_representante', models.CharField(default='', max_length=50)),
                ('email_representante', models.EmailField(default='', max_length=50)),
                ('telefono_representante', models.CharField(default='', max_length=15)),
                ('rut_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
