# Generated by Django 2.2.7 on 2020-03-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_tablaperfilempresa_direccion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='ciudad_empresa',
            field=models.CharField(default='', max_length=20, verbose_name='ciudad'),
        ),
    ]
