# Generated by Django 2.2.7 on 2020-03-14 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_auto_20200314_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='comuna_empresa',
            field=models.CharField(default='', max_length=20, verbose_name='comuna'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='direccion_empresa',
            field=models.CharField(default='', max_length=50, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='email_representante',
            field=models.EmailField(default='', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='experiencia_empresa',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='antigüedad'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='nombre_representante',
            field=models.CharField(default='', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='razon_social_empresa',
            field=models.CharField(default='', max_length=100, verbose_name='razon social'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='rut_representante',
            field=models.CharField(max_length=12, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='telefono_representante',
            field=models.CharField(default='', max_length=15, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='ventas_anuales_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaVentasAnuales', verbose_name='ventas anuales'),
        ),
    ]
