# Generated by Django 2.2.3 on 2019-07-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_tabla_resultados_construccion_tabla_resultados_manufactura_tabla_resultados_servicios_tabla_resultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_resultados_sustancias_peligrosas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('answer7', models.CharField(default='', max_length=2)),
                ('answer8', models.CharField(default='', max_length=2)),
                ('answer9', models.CharField(default='', max_length=2)),
                ('answer10', models.CharField(default='', max_length=2)),
                ('answer11', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_finales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_transporte', models.CharField(default='', max_length=2)),
                ('riesgo_construccion', models.CharField(default='', max_length=2)),
                ('riesgo_manufactura', models.CharField(default='', max_length=2)),
                ('riesgo_servicios', models.CharField(default='', max_length=2)),
                ('riesgo_dotacion', models.CharField(default='', max_length=2)),
                ('riesgo_gestion', models.CharField(default='', max_length=2)),
                ('riesgo_procesos', models.CharField(default='', max_length=2)),
                ('riesgo_explosivos', models.CharField(default='', max_length=2)),
                ('riesgo_electricidad', models.CharField(default='', max_length=2)),
                ('riesgo_sustancias_peligrosas', models.CharField(default='', max_length=2)),
                ('riesgo_altura', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_explosivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_electricidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_dotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('answer5', models.CharField(default='', max_length=2)),
                ('answer6', models.CharField(default='', max_length=2)),
                ('answer7', models.CharField(default='', max_length=2)),
                ('answer8', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_resultados_altura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(default='', max_length=2)),
                ('answer2', models.CharField(default='', max_length=2)),
                ('answer3', models.CharField(default='', max_length=2)),
                ('answer4', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_priorizacion_riesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidad_civil_empresa', models.CharField(default='', max_length=2)),
                ('equipos_moviles', models.CharField(default='', max_length=2)),
                ('transporte_terrestre', models.CharField(default='', max_length=2)),
                ('vehiculos_comerciales_livianos', models.CharField(default='', max_length=2)),
                ('vehiculos_comerciales_pesados', models.CharField(default='', max_length=2)),
                ('accidentes_personales', models.CharField(default='', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_usuario')),
                ('resultados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Tabla_resultados_finales')),
            ],
        ),
    ]
