# Generated by Django 2.2.3 on 2019-09-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_tablaperfilempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaPerfilEmpresa')),
            ],
        ),
    ]
