# Generated by Django 2.2.3 on 2020-01-13 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_auto_20200113_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablapoliza',
            name='prioridad',
            field=models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
