# Generated by Django 2.2.5 on 2019-11-17 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_auto_20191114_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaProcesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosProcesos',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('procesos', models.ManyToManyField(to='Poll.TablaProcesos')),
            ],
        ),
    ]
