# Generated by Django 2.2.7 on 2020-03-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_auto_20200314_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
        ),
        migrations.AddField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaManejoRiesgos'),
        ),
    ]
