# Generated by Django 2.2.7 on 2019-11-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_tablaprocesos_tablaresultadosprocesos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCertificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=100)),
            ],
        ),
    ]
