# Generated by Django 2.2.3 on 2019-11-20 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_tablaprocesos_tablaresultadosprocesos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_transporte', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tablaresultadosprocesos',
            name='construccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablaresultadosprocesos',
            name='manufactura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablaresultadosprocesos',
            name='servicios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablaresultadosprocesos',
            name='transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TablaResultadosTransporte',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ManyToManyField(to='Poll.TablaTransporte')),
            ],
        ),
    ]
