# Generated by Django 2.2.3 on 2020-01-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_tablapoliza_prioridad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablapoliza',
            old_name='nombre',
            new_name='nombre_poliza',
        ),
    ]
