# Generated by Django 2.2.7 on 2019-11-21 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_tablacertificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaResultadoCertificaciones',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('certificaciones', models.ManyToManyField(to='Poll.TablaCertificaciones')),
            ],
        ),
    ]
