# Generated by Django 2.2.3 on 2020-01-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_auto_20200113_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablaPrioridadBase',
        ),
    ]
