# Generated by Django 2.2.3 on 2019-08-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_auto_20190812_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_resultados_explosivos',
            name='answer6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabla_resultados_manufactura',
            name='answer7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tabla_resultados_sustancias_peligrosas',
            name='answer7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabla_resultados_sustancias_peligrosas',
            name='answer8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabla_resultados_sustancias_peligrosas',
            name='answer9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_construccion',
            name='answer7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer4',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer5',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer6',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer7',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_dotacion',
            name='answer8',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_gestion',
            name='answer4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tabla_resultados_transporte',
            name='answer10',
            field=models.CharField(default='', max_length=200),
        ),
    ]
