# Generated by Django 2.2.3 on 2019-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaperfilempresa',
            name='email_representante',
        ),
        migrations.RemoveField(
            model_name='tablaperfilempresa',
            name='nombre_representante',
        ),
        migrations.RemoveField(
            model_name='tablaperfilempresa',
            name='telefono_representante',
        ),
        migrations.RemoveField(
            model_name='tablaperfilempresa',
            name='ventas_anuales_empresa',
        ),
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='rut_empresa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
