# Generated by Django 2.2.3 on 2019-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0007_auto_20190814_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_perfil_usuario',
            name='razon_social_empresa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
