# Generated by Django 2.2.7 on 2019-11-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0007_tablaresultadocertificaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TablaResultadoCertificaciones',
            new_name='TablaResultadosCertificaciones',
        ),
    ]
