# Generated by Django 2.2.3 on 2019-09-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0007_auto_20190926_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaperfilusuario',
            name='empresa',
        ),
    ]
