# Generated by Django 2.2.3 on 2019-09-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0008_remove_tablaperfilusuario_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablaPerfilUsuario',
        ),
        migrations.AddField(
            model_name='tablaperfilempresa',
            name='email_representante',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tablaperfilempresa',
            name='nombre_representante',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tablaperfilempresa',
            name='telefono_representante',
            field=models.CharField(default='', max_length=15),
        ),
    ]
