# Generated by Django 2.2.3 on 2019-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0008_tabla_perfil_usuario_razon_social_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla_resultados_construccion',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='tabla_resultados_gestion',
            name='answer11',
        ),
        migrations.RemoveField(
            model_name='tabla_resultados_manufactura',
            name='answer7',
        ),
        migrations.RemoveField(
            model_name='tabla_resultados_transporte',
            name='answer10',
        ),
        migrations.AlterField(
            model_name='tabla_resultados_gestion',
            name='answer4',
            field=models.BooleanField(default=False),
        ),
    ]
