# Generated by Django 2.2.7 on 2019-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0008_auto_20191120_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaManejoRiesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manejo_riesgo', models.CharField(max_length=150)),
            ],
        ),
    ]
