# Generated by Django 2.2.2 on 2019-08-21 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0009_auto_20190821_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_resultados_transporte',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
