# Generated by Django 2.2.3 on 2020-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0009_auto_20200227_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablamanejoriesgos',
            name='cr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
