# Generated by Django 2.2.3 on 2019-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0009_auto_20190926_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='tablaperfilempresa',
            name='ventas_anuales_empresa',
            field=models.CharField(default='', max_length=50),
        ),
    ]
