# Generated by Django 2.2.3 on 2019-09-26 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0010_auto_20190926_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaperfilempresa',
            name='rut_empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
