# Generated by Django 2.2.3 on 2020-02-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0010_auto_20200227_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
        ),
        migrations.AddField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Poll.TablaManejoRiesgos'),
        ),
    ]
