# Generated by Django 2.2.2 on 2019-09-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0011_auto_20190827_0149'),
        ('Poll', '0009_auto_20190826_1924'),
    ]

    operations = [
    ]
