# Generated by Django 2.2.3 on 2020-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0011_auto_20200227_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
        ),
        migrations.AddField(
            model_name='tablaresultadosmanejoriesgo',
            name='opciones_manejo',
            field=models.ManyToManyField(to='Poll.TablaManejoRiesgos'),
        ),
    ]
