# Generated by Django 2.2.3 on 2020-02-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0012_auto_20200227_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaresultadoscertificaciones',
            name='certificaciones',
        ),
        migrations.RemoveField(
            model_name='tablaresultadoscertificaciones',
            name='id',
        ),
        migrations.DeleteModel(
            name='TablaCertificaciones',
        ),
        migrations.DeleteModel(
            name='TablaResultadosCertificaciones',
        ),
    ]
