# Generated by Django 2.2.7 on 2019-11-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0012_tablaresultadostiempopreven'),
        ('Poll', '0009_tablaresultadosservicios_tablaservicios'),
    ]

    operations = [
    ]
