# Generated by Django 2.2.3 on 2020-02-27 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0013_auto_20200227_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablatrabajosespecificos',
            name='ri',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
