# Generated by Django 2.2.7 on 2019-11-22 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0013_merge_20191121_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaManiExplosivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosManiExplosivos',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_expo', models.BooleanField()),
                ('tipos', models.ManyToManyField(to='Poll.TablaManiExplosivos')),
            ],
        ),
    ]
