# Generated by Django 2.2.7 on 2019-11-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0015_auto_20191122_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaSustancias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TablaResultadosSustancias',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_elec', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
                ('tipos', models.ManyToManyField(to='Poll.TablaSustancias')),
            ],
        ),
    ]
