# Generated by Django 2.2.3 on 2020-02-27 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0015_auto_20200227_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo1',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo2',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo3',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo4',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo5',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo6',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo7',
        ),
        migrations.RemoveField(
            model_name='tabladesignaciondotacion',
            name='campo8',
        ),
        migrations.AddField(
            model_name='tabladesignaciondotacion',
            name='nombre',
            field=models.CharField(default='(nombre)', max_length=100),
        ),
        migrations.AddField(
            model_name='tabladesignaciondotacion',
            name='poliza',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
