# Generated by Django 2.2.7 on 2019-11-22 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0016_tablaresultadossustancias_tablasustancias'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaTrabajosAltura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='tablaresultadossustancias',
            old_name='is_elec',
            new_name='is_sust',
        ),
        migrations.CreateModel(
            name='TablaResultadosAltura',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_alt', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
                ('tipos', models.ManyToManyField(to='Poll.TablaTrabajosAltura')),
            ],
        ),
    ]
