# Generated by Django 2.2.7 on 2019-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0022_auto_20191125_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaresultadoelectricidad',
            name='tipos',
            field=models.ManyToManyField(blank=True, to='Poll.TablaElectricidad'),
        ),
        migrations.AlterField(
            model_name='tablaresultadosaltura',
            name='tipos',
            field=models.ManyToManyField(blank=True, to='Poll.TablaTrabajosAltura'),
        ),
        migrations.AlterField(
            model_name='tablaresultadosmaniexplosivos',
            name='tipos',
            field=models.ManyToManyField(blank=True, to='Poll.TablaManiExplosivos'),
        ),
        migrations.AlterField(
            model_name='tablaresultadossustancias',
            name='tipos',
            field=models.ManyToManyField(blank=True, to='Poll.TablaSustancias'),
        ),
    ]
