# Generated by Django 2.2.7 on 2019-11-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0023_auto_20191126_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaresultadoelectricidad',
            name='is_elec',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
    ]
