# Generated by Django 2.2.3 on 2019-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0024_auto_20191126_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPrioridadBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=50)),
                ('prioridad', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
