# Generated by Django 2.2.7 on 2019-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0025_tablaprioridadbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaresultadoelectricidad',
            name='tipos',
            field=models.ManyToManyField(blank=True, null=True, to='Poll.TablaElectricidad'),
        ),
        migrations.AlterField(
            model_name='tablaresultadosaltura',
            name='tipos',
            field=models.ManyToManyField(blank=True, null=True, to='Poll.TablaTrabajosAltura'),
        ),
        migrations.AlterField(
            model_name='tablaresultadosmaniexplosivos',
            name='tipos',
            field=models.ManyToManyField(blank=True, null=True, to='Poll.TablaManiExplosivos'),
        ),
        migrations.AlterField(
            model_name='tablaresultadossustancias',
            name='tipos',
            field=models.ManyToManyField(blank=True, null=True, to='Poll.TablaSustancias'),
        ),
    ]
