# Generated by Django 2.2.7 on 2019-12-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0026_auto_20191213_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablaelectricidad',
            old_name='tipo',
            new_name='tipo_elec',
        ),
        migrations.RenameField(
            model_name='tablamaniexplosivos',
            old_name='tipo',
            new_name='tipo_exp',
        ),
        migrations.RenameField(
            model_name='tablaresultadoelectricidad',
            old_name='tipos',
            new_name='tipos_elec',
        ),
        migrations.RenameField(
            model_name='tablaresultadosaltura',
            old_name='tipos',
            new_name='tipos_alt',
        ),
        migrations.RenameField(
            model_name='tablaresultadosmaniexplosivos',
            old_name='tipos',
            new_name='tipos_exp',
        ),
        migrations.RenameField(
            model_name='tablaresultadossustancias',
            old_name='tipos',
            new_name='tipos_sust',
        ),
        migrations.RenameField(
            model_name='tablasustancias',
            old_name='tipo',
            new_name='tipo_sust',
        ),
        migrations.RenameField(
            model_name='tablatrabajosaltura',
            old_name='tipo',
            new_name='tipo_alt',
        ),
    ]
